install.packages('RPostgreSQL')
library(RPostgreSQL)
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv, dbname='aact',host='aact-db.ctti-clinicaltrials.org',port=5432,user=(username='chigomars'),password='Namcus123@')
aact_sample <- dbGetQuery(con,'select * from phase')
write.csv(aact_sample,file='aact_sample.csv')
print(aact_sample)
summary(con)
dbListTables(con)
dbListFields(con,'studies')
dbReadTable(con,'studies')
dbGetQuery(con,'select * from studies limit 10')
dbGetQuery(con,'select phase two from studies limit 10')
Query <- dbSendQuery(con,'select * from studies')
result <- dbFetch(Query, n=3)
result
summary(result)
aact_sample <- dbGetQuery(con,'select phase from studies')
write.csv(aact_sample,file='aact_sample.csv')
print(aact_sample)

library(microPop)
#check package version 
packageVersion("microPop")
M2=createDF(file=paste('Udeze file/MFG2.csv',sep=''))
M1=createDF(file=paste('Udeze file/MFG1.csv',sep=''))
res.SI=createDF(file=paste('Udeze file/resourceSI.csv',sep=''))
mic.SI=createDF(file=paste('Udeze file/microbeSI.csv',sep=''))

install.packages("vtable")
library(vtable)
library(RPostgreSQL)
drv <- dbDriver('PostgreSQL')

con <- dbConnect(drv, dbname="aact",host="aact-db.ctti-clinicaltrials.org", port=5432, user=(username='chigomars'), password='Namcus123@')

aact_sample <- dbGetQuery(con, "select distinct study_type from studies")
write.csv(aact_sample, file='aact_sample.csv')
print(aact_sample)
summary(aact_sample)
